export const SET_KEY_WORD = 'SET_KEY_WORD'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'
